### PR TITLE
Update Items.txt

### PR DESCRIPTION
**Pull request by Edge-R**

### CODE REVIEW

**Comment by Moffein** [comment]
Would you be able to update these strings? I'm updating Warbanner to be closer to the version in Risk of Rain Returns (removed armor, added health regen).

"ITEM_WARDONLEVEL_PICKUP_RISKYMOD": "Drop a Warbanner on level up or starting the Teleporter event. Grants allies damage, attack speed, movement speed, and health regeneration.",
"ITEM_WARDONLEVEL_DESC_RISKYMOD": "On <style=cIsUtility>level up</style> or starting the <style=cIsUtility>Teleporter event</style>, drop a banner that strengthens all allies within <style=cIsUtility>16m</style> <style=cStack>(+8m per stack)</style>. Raise <style=cIsDamage>damage</style> by <style=cIsDamage>15%</style>, and <style=cIsDamage>attack speed</style> and <style=cIsUtility>movement speed</style> by <style=cIsDamage>30%</style>. Also regenerate <style=cIsHealing>1%</style> of your <style=cIsHealing>health</style> every second.",

F4P0eXHbYAAZAv9

**Comment by Moffein** [comment]
Updated post, replaced references of "regeneration" with "healing".

**Comment by Edge-R** [comment]
"ITEM_WARDONLEVEL_PICKUP_RISKYMOD": "在升级或启动传送器事件时放下战旗。给予友方伤害提升、攻击速度、移动速度提升和再生。",
"ITEM_WARDONLEVEL_DESC_RISKYMOD": "在<style=cIsUtility>升级</style>或启动<style=cIsUtility>传送器事件</style>时,放下一个可以加强<style=cIsUtility>16米</style><style=cStack>（每层增加8）</style>范围内的所有友方。提升<style=cIsDamage>伤害</style><style=cIsDamage>15%</style>,和<style=cIsDamage>攻击速度</style>与<style=cIsUtility>移动速度</style><style=cIsDamage>30%</style>。并且每秒<style=cIsHealing>再生</style>其<style=cIsHealing>生命值</style>的<style=cIsHealing>1%</style>。",

**Comment by Moffein** [comment]
Thanks!

**Comment by JunJun5406** [comment]
fixed a few errors
[Items.txt](https://github.com/user-attachments/files/16627590/Items.txt)

**Comment by Moffein** [comment]
Hi, would you be able to update your translation for the latest update?
Here's a list of lines that were changed. I'd recommend downloading the latest version of the CN translation from the GitHub repo and editing that, since I already removed the lines marked as REMOVED.
https://github.com/Moffein/RiskyMod/blob/master/language/2.0.0%20TODO.txt

**Comment by JunJun5406** [comment]
[Items.txt](https://github.com/user-attachments/files/16941131/Items.txt)
[Keywords.txt](https://github.com/user-attachments/files/16941132/Keywords.txt)
[Survivors.txt](https://github.com/user-attachments/files/16941133/Survivors.txt)

**Comment by Moffein** [comment]
Thanks!

**Pull request merged**
