### PR TITLE
Update Survivors.txt

### PR DESCRIPTION
**Pull request by Edge-R**

### CODE REVIEW

**Comment by Moffein** [comment]
If you're still around, would you be able to translate these lines?

"COMMANDO_SPECIAL_ALT1_SCEPTER_NAME_RISKYMOD" : "Carpet Bomb",
"COMMANDO_SPECIAL_ALT1_SCEPTER_DESCRIPTION_RISKYMOD" : "Throw multiple grenades that explode for <style=cIsDamage>5x700% damage</style>. Can hold up to 2.",

No need for a pull request, you can just comment here.

**Comment by Edge-R** [comment]
"COMMANDO_SPECIAL_ALT1_SCEPTER_NAME_RISKYMOD" : "地毯式轰炸",
"COMMANDO_SPECIAL_ALT1_SCEPTER_DESCRIPTION_RISKYMOD" : "投掷多个手榴弹，爆炸造成<style=cIsDamage>5x700%的伤害</style>。最多充能2次。",

**Comment by Moffein** [comment]
Thanks!

**Comment by Moffein** [comment]
Would you be able to translate this line?

"TREEBOT_SPECIAL_ALT1_DESCRIPTION_RISKYMOD" : "<style=cIsDamage>Inject</style> an enemy for <style=cIsDamage>330% damage</style>. Allies <style=cIsHealing>heal</style> for <style=cIsHealing>10%</style> of the damage dealt to <style=cIsDamage>Injected</style> enemies. On death, drop <style=cIsHealing>healing fruits</style> that heal for <style=cIsHealing>25% HP</style>."

**Comment by Edge-R** [comment]
No problem. 

"TREEBOT_SPECIAL_ALT1_DESCRIPTION_RISKYMOD" : "一个敌人造成的伤害，对被的敌人造成伤害的将友方。敌人死亡时将掉落恢复。"

**Comment by Edge-R** [comment]
No problem.

"TREEBOT_SPECIAL_ALT1_DESCRIPTION_RISKYMOD" : "<style=cIsDamage>注入</style>一个敌人造成<style=cIsDamage>330%</style>的伤害，对被<style=cIsDamage>注入</style>的敌人造成伤害的<style=cIsHealing>10%</style>将<style=cIsHealing>治疗</style>友方。敌人死亡时将掉落<style=cIsHealing>治疗果实</style>恢复<style=cIsHealing>25%生命值</style>。"

**Comment by Moffein** [comment]
Adding some stuff from Risk of Rain Returns, could you translate this when you get the chance? Skill name is already translated using the CN language file from that game.

"BANDIT2_REVOLVER_STANDOFF_NAME_RISKYMOD" : "对峙",
"BANDIT2_REVOLVER_STANDOFF_DESCRIPTION_RISKYMOD" : "Revolver kills <style=cIsDamage>increase damage by 20%</style> for 15 seconds. Stacks up to <style=cIsDamage>5</style> times.",

**Comment by Edge-R** [comment]
"BANDIT2_REVOLVER_STANDOFF_DESCRIPTION_RISKYMOD" : "使用左轮手枪击杀将<style=cIsDamage>提升20%伤害</style>持续15秒。最多叠加<style=cIsDamage>5</style>次。",

**Comment by Moffein** [comment]
Thanks!

**Pull request closed without merging**
